# Generated by Django 4.0.6 on 2022-07-27 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Init', 'Init'), ('Pending', 'Pending'), ('Successful', 'Successful'), ('Rejected', 'Rejected')], default='Init', max_length=30, verbose_name='Status')),
                ('form_four_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place of Birth')),
                ('place_of_olevo_completion', models.CharField(max_length=255, verbose_name='Region for olevo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
