# Generated by Django 4.0.6 on 2022-07-28 11:46

import autoslug.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255, verbose_name='Course name')),
                ('course_years', models.IntegerField()),
                ('level', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma')], default='Certificate', max_length=50, verbose_name='Level')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='course_title', unique=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
            managers=[
                ('certificateObjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
