# Generated by Django 4.0.6 on 2022-08-02 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=2, verbose_name='Subject')),
            ],
        ),
        migrations.CreateModel(
            name='MyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Applied', 'Applied'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Applied', max_length=50, verbose_name='Application state')),
                ('education', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma')], default='Certificate', max_length=50, verbose_name='Education')),
                ('has_olevo_certificate', models.BooleanField(default=False, verbose_name='Has certificate')),
                ('form_four_Number', models.CharField(max_length=255, verbose_name='Form four Number')),
                ('region_of_residence', models.CharField(max_length=255, verbose_name='Region of Residence')),
                ('district_of_residence', models.CharField(max_length=255, verbose_name='District of Residence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('results', models.ManyToManyField(to='myapp.results')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
            managers=[
                ('appliedObjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
