# Generated by Django 4.0.6 on 2022-08-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_myapplication_results_myapplication_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapplication',
            name='selected_course',
            field=models.CharField(default='Journalism', max_length=255, verbose_name='Selected Course'),
            preserve_default=False,
        ),
    ]
